---
title: "AnVIL Collection"
site: bookdown::bookdown_site
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
description: Description about Course/Book.
favicon: assets/AnVIL_style/anvil_favicon.ico
---

# Courses and Guides {-}

Please check out our full collection of AnVIL and related resources below!

This page was last updated on `r Sys.time()`

## AnVIL Resources {-}

```{r, echo = FALSE, message = FALSE, warning = FALSE}
source("scripts/render_collection.R")

knitr::kable(make_collection_table(exclude_gdscn_from_table = TRUE), format = "html")
```

## GDSCN Resources {-}

```{r, echo = FALSE, message = FALSE, warning = FALSE}
source("scripts/render_collection.R")

knitr::kable(make_collection_table(make_gsdcn_only_table = TRUE), format = "html")
```

# YouTube Videos {-}

## AnVIL "Shorts" (AnVIL in 2 minutes) {-}

```{r, echo = FALSE, message = FALSE, warning = FALSE}
source("scripts/render_youtube_list.R")

knitr::kable(make_youtube_shorts_table(), format = "html")
```
