
name: Build Collection

on:
  workflow_call:
    inputs:
      render-type:
        required: true
        type: string
      repository:
        type: string
        required: true
    secrets:
      gh_pat:
        required: true
      yt_key:
        required: true

jobs:
  build-repo-collection:
    name: Gather Repositories
    runs-on: ubuntu-latest
    container:
      image: jhudsl/course_template:main

    steps:
      - name: Checkout files
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.gh_pat }}

      - name: Configure git
        run: |
          git config --local user.email "itcrtrainingnetwork@gmail.com"
          git config --local user.name "jhudsl-robot"
        shell: bash

      - name: Merge if rendering preview
        if: ${{ inputs.render-type == 'preview' }}
        run: |
          branch_name='preview-${{ github.event.pull_request.number }}'
          git fetch --all
          git checkout $branch_name
          git merge -s recursive --strategy-option=theirs origin/${{ github.head_ref }} --allow-unrelated-histories
        shell: bash

      - name: Checkout if main
        if: ${{ inputs.render-type == 'main' }}
        run: |
          git fetch --all
          git checkout main
        shell: bash

      - name: Query API and make repo collection
        id: anvil_repos
        env:
          GH_PAT: ${{ secrets.gh_pat }}
        run: |
          sudo apt-get install libcurl4-openssl-dev

          # Need a clean render of the collection every time
          rm -f resources/collection.tsv
          rm -f index.html

          # Run repo check script
          Rscript --vanilla "scripts/query_collection.R" --git_pat "$GH_PAT"

      - name: Archive collection
        uses: actions/upload-artifact@v2
        with:
          name: collection
          path: resources/collection.tsv
          
      - name: Query Youtube API
        id: anvil_channel
        env:
          YT_KEY: ${{ secrets.yt_key }}
        run: |
          sudo apt-get install libcurl4-openssl-dev

          # Need a clean render of the youtube data every time
          # rm -f resources/youtube_metadata.tsv

          # Run script
          Rscript --vanilla "scripts/query_youtube.R" --yt_key "$YT_KEY"
          
      - name: Archive youtube results
        uses: actions/upload-artifact@v2
        with:
          name: youtube_metadata
          path: resources/youtube_metadata.csv
          
      - name: Archive youtube `shorts` playlist results
        uses: actions/upload-artifact@v2
        with:
          name: youtube_shorts_data
          path: resources/youtube_shorts_data.csv
          
      - name: Archive youtube `demos` playlist results
        uses: actions/upload-artifact@v2
        with:
          name: youtube_demos_data
          path: resources/youtube_demos_data.csv
          
      - name: Archive youtube `getting started` playlist results
        uses: actions/upload-artifact@v2
        with:
          name: youtube_getting_started_data
          path: resources/youtube_getting_started_data.csv
          
      - name: Archive youtube `WDL` playlist results
        uses: actions/upload-artifact@v2
        with:
          name: youtube_getting_anvil_wdl_data
          path: resources/youtube_anvil_wdl_data.csv
          
      - name: Archive youtube `gdscn sars` playlist results
        uses: actions/upload-artifact@v2
        with:
          name: youtube_getting_gdscn_sars_data
          path: resources/youtube_gdscn_sars_data.csv
                    
      - name: Archive youtube `gdscn soil protocols` playlist results
        uses: actions/upload-artifact@v2
        with:
          name: youtube_getting_gdscn_soil_project_data
          path: resources/youtube_gdscn_soil_project_data.csv

      # Commit the created files
      - name: Commit .csv files to main
        if: ${{ inputs.render-type == 'main' }}
        env:
          GH_PAT: ${{ secrets.gh_pat }}
        run: |
          git add --force resources/collection.tsv resources/youtube_metadata.csv resources/youtube_shorts_data.csv resources/youtube_demos_data.csv resources/youtube_getting_started_data.csv resources/youtube_gdscn_sars_data.csv
          git commit -m 'Add API query files' || echo "No changes to commit"
          git fetch
          git merge -s recursive --strategy-option=ours origin/main --allow-unrelated-histories
          git push -u origin main || echo "No changes to push"

      - name: Commit .tsv files to preview
        if: ${{ inputs.render-type == 'preview' }}
        run: |
          branch_name='preview-${{ github.event.pull_request.number }}'
          git add --force resources/collection.tsv resources/youtube_metadata.csv resources/youtube_shorts_data.csv resources/youtube_demos_data.csv resources/youtube_getting_started_data.csv resources/youtube_gdscn_sars_data.csv
          git commit -m 'Add API query files' || echo "No changes to commit"
          git fetch
          git merge -s recursive --strategy-option=theirs origin/${{ github.head_ref }} --allow-unrelated-histories
          git push --force origin $branch_name || echo "No changes to commit"
